=== leadex/mulesoft-meetup-containerization/api/fins-fis-sys-api/src/main/resources/api/accelerator-cim-market-library/1.2.0/jsonSchemas/BillingFrequencySchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/BillingFrequency",
  "definitions": {
    "BillingFrequency": {
      "type": "object",
      "example": {
        "billingFrequencyName": "sint proident ex",
        "name": "sed exercitation Excepteur tempor",
        "id": null,
        "auditInfo": {
          "isDeleted": null,
          "createdBy": "proident",
          "updatedBy": "veniam ea anim",
          "updatedDate": "1968-04-06T08:23:47.481Z",
          "createdDate": "1968-09-16T20:49:34.447Z"
        }
      },
      "additionalProperties": true,
      "required": [
        "billingFrequencyName",
        "name",
        "id"
      ],
      "properties": {
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "name": {
          "type": "string"
        },
        "billingFrequencyName": {
          "type": "string"
        },
        "auditInfo": {
          "description": "Defines standard system audit fields available for most types",
          "type": "object",
          "example": {
            "isDeleted": true,
            "createdBy": "commodo minim dolore est",
            "updatedBy": "dolor quis nulla",
            "updatedDate": "1950-01-23T19:52:29.659Z",
            "createdDate": "1950-01-23T19:52:29.659Z"
          },
          "additionalProperties": true,
          "required": [
            "isDeleted",
            "createdBy",
            "updatedBy",
            "updatedDate",
            "createdDate"
          ],
          "properties": {
            "createdDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was created"
            },
            "createdBy": {
              "type": "string",
              "description": "Identifies the system or user which created the entity"
            },
            "updatedDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was last updated"
            },
            "updatedBy": {
              "type": "string",
              "description": "Identifies the system or user which last updated the entity"
            },
            "isDeleted": {
              "anyOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Indicates whether or not the entity has been soft-deleted"
            }
          }
        }
      }
    }
  }
}

=== leadex/mulesoft-meetup-containerization/api/fins-fis-sys-api/src/main/resources/api/accelerator-cim-market-library/1.2.0/examples/BillingFrequencyExample.json
{
  "billingFrequencyName": "eiusmod cupidatat",
  "name": "ut tempor est magna",
  "id": "incididunt occaecat",
  "auditInfo": {
    "isDeleted": false,
    "createdBy": "aliquip tempor",
    "updatedBy": "et",
    "updatedDate": "2014-11-13T20:16:24.482Z",
    "createdDate": "1956-04-09T21:25:51.962Z"
  }
}
