=== leadex/mulesoft-meetup-containerization/api/fins-fis-sys-api/src/main/resources/api/accelerator-cim-market-library/1.2.0/jsonSchemas/ContactPointPhoneSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/ContactPointPhone",
  "definitions": {
    "ContactPointPhone": {
      "type": "object",
      "example": {
        "contactPointType": [
          "elit dolore in consequat"
        ],
        "id": null,
        "telephoneNumber": "aliqua Lorem est",
        "activeFromDate": "2019-12-07",
        "profileOccurrenceCount": -42006111,
        "formattedE164PhoneNumber": "elit labore sunt Ut",
        "isSMSCapable": false,
        "bestTimeToContactStartTime": "00:00:01",
        "phoneCountryCode": "consectetur cillum commodo voluptate proident",
        "forPersonalUse": null,
        "profileFirstCreatedDate": null,
        "activeToDate": null,
        "shortCode": null,
        "primaryFlag": null,
        "isFaxCapable": true,
        "countryName": "amet dolor commodo esse Excepteur",
        "bestTimeToContactEndTime": "00:00:01",
        "party": [
          "aute aliquip ex in"
        ],
        "partyRole": [
          "eu"
        ],
        "primaryPhoneType": "in ad est",
        "profileLastUpdatedDate": "00:00:01",
        "formattedInternationalPhoneNumber": "culpa dolor reprehenderit",
        "name": "anim nisi",
        "forBusinessUse": null,
        "formattedNationalPhoneNumber": "culpa",
        "areaCode": "irure",
        "extensionNumber": "deserunt non adipisicing qui",
        "auditInfo": {
          "isDeleted": true,
          "createdBy": "quis",
          "updatedBy": "est exercitation",
          "updatedDate": null,
          "createdDate": null
        }
      },
      "additionalProperties": true,
      "required": [
        "contactPointType",
        "id",
        "telephoneNumber",
        "activeFromDate"
      ],
      "properties": {
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "name": {
          "type": "string"
        },
        "primaryFlag": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "bestTimeToContactStartTime": {
          "anyOf": [
            {
              "type": "string",
              "format": "time"
            },
            {
              "type": "null"
            }
          ]
        },
        "profileLastUpdatedDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "time"
            },
            {
              "type": "null"
            }
          ]
        },
        "partyRole": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "activeFromDate": {
          "type": "string",
          "format": "date"
        },
        "activeToDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ]
        },
        "profileOccurrenceCount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "profileFirstCreatedDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "time"
            },
            {
              "type": "null"
            }
          ]
        },
        "bestTimeToContactEndTime": {
          "anyOf": [
            {
              "type": "string",
              "format": "time"
            },
            {
              "type": "null"
            }
          ]
        },
        "party": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "contactPointType": {
          "type": "array",
          "items": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "object",
                "additionalProperties": true,
                "required": [
                  "id",
                  "name"
                ],
                "properties": {
                  "id": {
                    "anyOf": [
                      {
                        "type": "string"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "name": {
                    "type": "string"
                  },
                  "optInPriority": {
                    "anyOf": [
                      {
                        "type": "integer"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "auditInfo": {
                    "description": "Defines standard system audit fields available for most types",
                    "type": "object",
                    "example": {
                      "isDeleted": true,
                      "createdBy": "commodo minim dolore est",
                      "updatedBy": "dolor quis nulla",
                      "updatedDate": "1950-01-23T19:52:29.659Z",
                      "createdDate": "1950-01-23T19:52:29.659Z"
                    },
                    "additionalProperties": true,
                    "required": [
                      "isDeleted",
                      "createdBy",
                      "updatedBy",
                      "updatedDate",
                      "createdDate"
                    ],
                    "properties": {
                      "createdDate": {
                        "anyOf": [
                          {
                            "type": "string",
                            "format": "date-time"
                          },
                          {
                            "type": "null"
                          }
                        ],
                        "description": "Timestamp of when the entity was created"
                      },
                      "createdBy": {
                        "type": "string",
                        "description": "Identifies the system or user which created the entity"
                      },
                      "updatedDate": {
                        "anyOf": [
                          {
                            "type": "string",
                            "format": "date-time"
                          },
                          {
                            "type": "null"
                          }
                        ],
                        "description": "Timestamp of when the entity was last updated"
                      },
                      "updatedBy": {
                        "type": "string",
                        "description": "Identifies the system or user which last updated the entity"
                      },
                      "isDeleted": {
                        "anyOf": [
                          {
                            "type": "boolean"
                          },
                          {
                            "type": "null"
                          }
                        ],
                        "description": "Indicates whether or not the entity has been soft-deleted"
                      }
                    }
                  }
                }
              }
            ]
          }
        },
        "forBusinessUse": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "forPersonalUse": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "auditInfo": {
          "description": "Defines standard system audit fields available for most types",
          "type": "object",
          "example": {
            "isDeleted": true,
            "createdBy": "commodo minim dolore est",
            "updatedBy": "dolor quis nulla",
            "updatedDate": "1950-01-23T19:52:29.659Z",
            "createdDate": "1950-01-23T19:52:29.659Z"
          },
          "additionalProperties": true,
          "required": [
            "isDeleted",
            "createdBy",
            "updatedBy",
            "updatedDate",
            "createdDate"
          ],
          "properties": {
            "createdDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was created"
            },
            "createdBy": {
              "type": "string",
              "description": "Identifies the system or user which created the entity"
            },
            "updatedDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was last updated"
            },
            "updatedBy": {
              "type": "string",
              "description": "Identifies the system or user which last updated the entity"
            },
            "isDeleted": {
              "anyOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Indicates whether or not the entity has been soft-deleted"
            }
          }
        },
        "extensionNumber": {
          "type": "string"
        },
        "phoneCountryCode": {
          "type": "string"
        },
        "countryName": {
          "type": "string"
        },
        "areaCode": {
          "type": "string"
        },
        "isSMSCapable": {
          "type": "boolean"
        },
        "shortCode": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "formattedInternationalPhoneNumber": {
          "type": "string"
        },
        "primaryPhoneType": {
          "type": "string"
        },
        "isFaxCapable": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "formattedE164PhoneNumber": {
          "type": "string"
        },
        "formattedNationalPhoneNumber": {
          "type": "string"
        },
        "telephoneNumber": {
          "type": "string"
        }
      }
    }
  }
}

=== leadex/mulesoft-meetup-containerization/api/fins-fis-sys-api/src/main/resources/api/accelerator-cim-market-library/1.2.0/examples/ContactPointPhoneExample.json
{
  "contactPointType": [
    {
      "id": "tempor",
      "name": "proident ullamco irure id",
      "optInPriority": null,
      "auditInfo": {
        "isDeleted": null,
        "createdBy": "laboris",
        "updatedBy": "sed deserunt do",
        "updatedDate": "2010-07-05T08:03:48.491Z",
        "createdDate": "1968-03-30T05:30:53.42Z"
      }
    }
  ],
  "id": "incididunt quis et labore",
  "telephoneNumber": "cillum",
  "activeFromDate": "2006-09-02",
  "profileLastUpdatedDate": "00:00:01",
  "isSMSCapable": true,
  "bestTimeToContactEndTime": "00:00:01",
  "activeToDate": "1959-12-28",
  "forPersonalUse": true,
  "profileOccurrenceCount": null,
  "formattedE164PhoneNumber": "cupidatat consequat esse",
  "primaryFlag": null,
  "auditInfo": {
    "isDeleted": false,
    "createdBy": "incididunt",
    "updatedBy": "velit incididunt in",
    "updatedDate": null,
    "createdDate": "1978-02-14T20:01:51.549Z"
  },
  "isFaxCapable": false,
  "party": [
    "id qui officia magna"
  ],
  "formattedInternationalPhoneNumber": "aute id",
  "partyRole": [
    "anim nulla occaecat fugiat est"
  ],
  "forBusinessUse": true,
  "extensionNumber": "irure do"
}
