=== leadex/mulesoft-meetup-containerization/api/fins-fis-sys-api/src/main/resources/api/accelerator-cim-market-library/1.2.0/jsonSchemas/ContactPointAddressSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/ContactPointAddress",
  "definitions": {
    "ContactPointAddress": {
      "type": "object",
      "example": {
        "addressLine1": "cupidatat officia id Lorem",
        "contactPointType": [
          {
            "id": "aliqua consequat in sint laboris",
            "name": "Ut in ipsum ex"
          }
        ],
        "id": null,
        "activeFromDate": "1967-04-22",
        "forBusinessUse": false,
        "geoAccuracy": null,
        "cityName": "in ex voluptate occaecat eu",
        "geoLatitude": -6663796,
        "bestTimeToContactStartTime": "00:00:01",
        "auditInfo": {
          "isDeleted": null,
          "createdBy": "adipisicing in",
          "updatedBy": "consectetur aute cupidatat deserunt nulla",
          "updatedDate": null,
          "createdDate": null
        },
        "forPersonalUse": false,
        "activeToDate": "1965-03-15",
        "isUsedForShipping": true,
        "stateProvinceName": "occaecat Lorem eiusmod in ut",
        "addressLine4": "labore",
        "contactPhone": [
          "minim exercitation dolore"
        ],
        "addressLine3": "culpa id eu",
        "profileFirstCreatedDate": null
      },
      "additionalProperties": true,
      "required": [
        "addressLine1",
        "contactPointType",
        "id",
        "activeFromDate"
      ],
      "properties": {
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "name": {
          "type": "string"
        },
        "primaryFlag": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "bestTimeToContactStartTime": {
          "anyOf": [
            {
              "type": "string",
              "format": "time"
            },
            {
              "type": "null"
            }
          ]
        },
        "profileLastUpdatedDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "time"
            },
            {
              "type": "null"
            }
          ]
        },
        "partyRole": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "activeFromDate": {
          "type": "string",
          "format": "date"
        },
        "activeToDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ]
        },
        "profileOccurrenceCount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "profileFirstCreatedDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "time"
            },
            {
              "type": "null"
            }
          ]
        },
        "bestTimeToContactEndTime": {
          "anyOf": [
            {
              "type": "string",
              "format": "time"
            },
            {
              "type": "null"
            }
          ]
        },
        "party": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "contactPointType": {
          "type": "array",
          "items": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "object",
                "additionalProperties": true,
                "required": [
                  "id",
                  "name"
                ],
                "properties": {
                  "id": {
                    "anyOf": [
                      {
                        "type": "string"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "name": {
                    "type": "string"
                  },
                  "optInPriority": {
                    "anyOf": [
                      {
                        "type": "integer"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "auditInfo": {
                    "description": "Defines standard system audit fields available for most types",
                    "type": "object",
                    "example": {
                      "isDeleted": true,
                      "createdBy": "commodo minim dolore est",
                      "updatedBy": "dolor quis nulla",
                      "updatedDate": "1950-01-23T19:52:29.659Z",
                      "createdDate": "1950-01-23T19:52:29.659Z"
                    },
                    "additionalProperties": true,
                    "required": [
                      "isDeleted",
                      "createdBy",
                      "updatedBy",
                      "updatedDate",
                      "createdDate"
                    ],
                    "properties": {
                      "createdDate": {
                        "anyOf": [
                          {
                            "type": "string",
                            "format": "date-time"
                          },
                          {
                            "type": "null"
                          }
                        ],
                        "description": "Timestamp of when the entity was created"
                      },
                      "createdBy": {
                        "type": "string",
                        "description": "Identifies the system or user which created the entity"
                      },
                      "updatedDate": {
                        "anyOf": [
                          {
                            "type": "string",
                            "format": "date-time"
                          },
                          {
                            "type": "null"
                          }
                        ],
                        "description": "Timestamp of when the entity was last updated"
                      },
                      "updatedBy": {
                        "type": "string",
                        "description": "Identifies the system or user which last updated the entity"
                      },
                      "isDeleted": {
                        "anyOf": [
                          {
                            "type": "boolean"
                          },
                          {
                            "type": "null"
                          }
                        ],
                        "description": "Indicates whether or not the entity has been soft-deleted"
                      }
                    }
                  }
                }
              }
            ]
          }
        },
        "forBusinessUse": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "forPersonalUse": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "auditInfo": {
          "description": "Defines standard system audit fields available for most types",
          "type": "object",
          "example": {
            "isDeleted": true,
            "createdBy": "commodo minim dolore est",
            "updatedBy": "dolor quis nulla",
            "updatedDate": "1950-01-23T19:52:29.659Z",
            "createdDate": "1950-01-23T19:52:29.659Z"
          },
          "additionalProperties": true,
          "required": [
            "isDeleted",
            "createdBy",
            "updatedBy",
            "updatedDate",
            "createdDate"
          ],
          "properties": {
            "createdDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was created"
            },
            "createdBy": {
              "type": "string",
              "description": "Identifies the system or user which created the entity"
            },
            "updatedDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was last updated"
            },
            "updatedBy": {
              "type": "string",
              "description": "Identifies the system or user which last updated the entity"
            },
            "isDeleted": {
              "anyOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Indicates whether or not the entity has been soft-deleted"
            }
          }
        },
        "isUsedForShipping": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "stateProvinceName": {
          "type": "string"
        },
        "addressLine3": {
          "type": "string"
        },
        "countryName": {
          "type": "string"
        },
        "postalCodeText": {
          "type": "string"
        },
        "geoLatitude": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "addressLine2": {
          "type": "string"
        },
        "addressLine4": {
          "type": "string"
        },
        "geoAccuracy": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "contactPhone": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "geoLongitude": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "addressLine1": {
          "type": "string"
        },
        "cityName": {
          "type": "string"
        },
        "isUsedForBilling": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        }
      }
    }
  }
}

=== leadex/mulesoft-meetup-containerization/api/fins-fis-sys-api/src/main/resources/api/accelerator-cim-market-library/1.2.0/examples/ContactPointAddressExample.json
{
  "addressLine1": "minim exercitation anim",
  "contactPointType": [
    "reprehenderit"
  ],
  "id": "minim culpa Duis eu dolor",
  "activeFromDate": "1946-08-14",
  "cityName": "proident ullamco ex",
  "geoLatitude": null,
  "party": [
    "in"
  ],
  "addressLine2": "minim nulla amet nisi",
  "primaryFlag": null,
  "geoLongitude": -41602494,
  "bestTimeToContactEndTime": "00:00:01",
  "isUsedForBilling": null,
  "stateProvinceName": "ut ex irure eu qui",
  "bestTimeToContactStartTime": "00:00:01",
  "postalCodeText": "et"
}
