=== leadex/mulesoft-meetup-containerization/api/fins-fis-sys-api/src/main/resources/api/accelerator-cim-market-library/1.2.0/jsonSchemas/ContactPointEmailSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/ContactPointEmail",
  "definitions": {
    "ContactPointEmail": {
      "type": "object",
      "example": {
        "emailAddress": "ex",
        "contactPointType": [
          {
            "id": null,
            "name": "id tempor est adipisicing mollit",
            "optInPriority": 67432794,
            "auditInfo": {
              "isDeleted": null,
              "createdBy": "in reprehenderit ut",
              "updatedBy": "ad reprehenderit adipisicing",
              "updatedDate": null,
              "createdDate": null
            }
          }
        ],
        "id": null,
        "activeFromDate": "1971-07-06",
        "partyRole": [
          "adipisicing cupidatat"
        ],
        "name": "Ut mollit anim",
        "party": [
          "ea"
        ],
        "profileLastUpdatedDate": null,
        "auditInfo": {
          "isDeleted": null,
          "createdBy": "in fugiat deserunt officia ex",
          "updatedBy": "consectetur aute velit dolore culpa",
          "updatedDate": "1973-08-06T19:25:53.202Z",
          "createdDate": "2007-11-27T12:31:32.024Z"
        },
        "forBusinessUse": null,
        "emailLatestBounceDateTime": "1995-05-17",
        "bestTimeToContactStartTime": "00:00:01",
        "emailMailBox": "officia reprehenderit proident",
        "forPersonalUse": true,
        "emailDomain": "dolore est velit"
      },
      "additionalProperties": true,
      "required": [
        "emailAddress",
        "contactPointType",
        "id",
        "activeFromDate"
      ],
      "properties": {
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "name": {
          "type": "string"
        },
        "primaryFlag": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "bestTimeToContactStartTime": {
          "anyOf": [
            {
              "type": "string",
              "format": "time"
            },
            {
              "type": "null"
            }
          ]
        },
        "profileLastUpdatedDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "time"
            },
            {
              "type": "null"
            }
          ]
        },
        "partyRole": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "activeFromDate": {
          "type": "string",
          "format": "date"
        },
        "activeToDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ]
        },
        "profileOccurrenceCount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "profileFirstCreatedDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "time"
            },
            {
              "type": "null"
            }
          ]
        },
        "bestTimeToContactEndTime": {
          "anyOf": [
            {
              "type": "string",
              "format": "time"
            },
            {
              "type": "null"
            }
          ]
        },
        "party": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "contactPointType": {
          "type": "array",
          "items": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "object",
                "additionalProperties": true,
                "required": [
                  "id",
                  "name"
                ],
                "properties": {
                  "id": {
                    "anyOf": [
                      {
                        "type": "string"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "name": {
                    "type": "string"
                  },
                  "optInPriority": {
                    "anyOf": [
                      {
                        "type": "integer"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "auditInfo": {
                    "description": "Defines standard system audit fields available for most types",
                    "type": "object",
                    "example": {
                      "isDeleted": true,
                      "createdBy": "commodo minim dolore est",
                      "updatedBy": "dolor quis nulla",
                      "updatedDate": "1950-01-23T19:52:29.659Z",
                      "createdDate": "1950-01-23T19:52:29.659Z"
                    },
                    "additionalProperties": true,
                    "required": [
                      "isDeleted",
                      "createdBy",
                      "updatedBy",
                      "updatedDate",
                      "createdDate"
                    ],
                    "properties": {
                      "createdDate": {
                        "anyOf": [
                          {
                            "type": "string",
                            "format": "date-time"
                          },
                          {
                            "type": "null"
                          }
                        ],
                        "description": "Timestamp of when the entity was created"
                      },
                      "createdBy": {
                        "type": "string",
                        "description": "Identifies the system or user which created the entity"
                      },
                      "updatedDate": {
                        "anyOf": [
                          {
                            "type": "string",
                            "format": "date-time"
                          },
                          {
                            "type": "null"
                          }
                        ],
                        "description": "Timestamp of when the entity was last updated"
                      },
                      "updatedBy": {
                        "type": "string",
                        "description": "Identifies the system or user which last updated the entity"
                      },
                      "isDeleted": {
                        "anyOf": [
                          {
                            "type": "boolean"
                          },
                          {
                            "type": "null"
                          }
                        ],
                        "description": "Indicates whether or not the entity has been soft-deleted"
                      }
                    }
                  }
                }
              }
            ]
          }
        },
        "forBusinessUse": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "forPersonalUse": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "auditInfo": {
          "description": "Defines standard system audit fields available for most types",
          "type": "object",
          "example": {
            "isDeleted": true,
            "createdBy": "commodo minim dolore est",
            "updatedBy": "dolor quis nulla",
            "updatedDate": "1950-01-23T19:52:29.659Z",
            "createdDate": "1950-01-23T19:52:29.659Z"
          },
          "additionalProperties": true,
          "required": [
            "isDeleted",
            "createdBy",
            "updatedBy",
            "updatedDate",
            "createdDate"
          ],
          "properties": {
            "createdDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was created"
            },
            "createdBy": {
              "type": "string",
              "description": "Identifies the system or user which created the entity"
            },
            "updatedDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was last updated"
            },
            "updatedBy": {
              "type": "string",
              "description": "Identifies the system or user which last updated the entity"
            },
            "isDeleted": {
              "anyOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Indicates whether or not the entity has been soft-deleted"
            }
          }
        },
        "emailLatestBounceReasonText": {
          "type": "string"
        },
        "emailMailBox": {
          "type": "string"
        },
        "emailDomain": {
          "type": "string"
        },
        "emailAddress": {
          "type": "string"
        },
        "emailLatestBounceDateTime": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ]
        }
      }
    }
  }
}

=== leadex/mulesoft-meetup-containerization/api/fins-fis-sys-api/src/main/resources/api/accelerator-cim-market-library/1.2.0/examples/ContactPointEmailExample.json
{
  "emailAddress": "occaecat incididunt",
  "contactPointType": [
    {
      "id": null,
      "name": "dolor fugiat do"
    }
  ],
  "id": "sed nisi",
  "activeFromDate": "1951-07-03",
  "bestTimeToContactEndTime": "00:00:01",
  "emailLatestBounceReasonText": "veniam incididunt labore in",
  "emailLatestBounceDateTime": null,
  "activeToDate": "1993-05-12",
  "emailDomain": "nisi",
  "auditInfo": {
    "isDeleted": false,
    "createdBy": "voluptate",
    "updatedBy": "adipisicing nulla qui",
    "updatedDate": null,
    "createdDate": "1950-04-02T11:20:28.713Z"
  },
  "profileFirstCreatedDate": null,
  "profileOccurrenceCount": null,
  "party": [
    "aliquip sunt exercitation"
  ],
  "name": "commodo ad quis eiusmod aliqua",
  "bestTimeToContactStartTime": "00:00:01",
  "partyRole": [
    "mollit quis ea in"
  ],
  "forBusinessUse": null,
  "emailMailBox": "est Excepteur",
  "primaryFlag": false,
  "forPersonalUse": null,
  "profileLastUpdatedDate": null
}
