=== leadex/mulesoft-meetup-containerization/api/fins-fis-sys-api/src/main/resources/api/accelerator-cim-market-library/1.2.0/jsonSchemas/ContactPointLocationSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/ContactPointLocation",
  "definitions": {
    "ContactPointLocation": {
      "type": "object",
      "example": {
        "contactPointType": [
          {
            "id": "dolore do",
            "name": "nisi quis dolore dolor",
            "auditInfo": {
              "isDeleted": false,
              "createdBy": "Excepteur dolor proident",
              "updatedBy": "Ut id Lorem",
              "updatedDate": null,
              "createdDate": "1970-01-11T00:43:18.137Z"
            },
            "optInPriority": -19991644
          }
        ],
        "id": null,
        "activeFromDate": "2006-10-27",
        "profileFirstCreatedDate": "00:00:01",
        "profileLastUpdatedDate": null,
        "partyRole": [
          "occaecat consequat officia"
        ],
        "bestTimeToContactEndTime": null,
        "auditInfo": {
          "isDeleted": null,
          "createdBy": "sunt dolor magna pariatur do",
          "updatedBy": "magna in reprehenderit",
          "updatedDate": null,
          "createdDate": "1965-01-24T09:51:19.915Z"
        },
        "primaryFlag": false
      },
      "additionalProperties": true,
      "required": [
        "contactPointType",
        "id",
        "activeFromDate"
      ],
      "properties": {
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "name": {
          "type": "string"
        },
        "primaryFlag": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "bestTimeToContactStartTime": {
          "anyOf": [
            {
              "type": "string",
              "format": "time"
            },
            {
              "type": "null"
            }
          ]
        },
        "profileLastUpdatedDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "time"
            },
            {
              "type": "null"
            }
          ]
        },
        "partyRole": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "activeFromDate": {
          "type": "string",
          "format": "date"
        },
        "activeToDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ]
        },
        "profileOccurrenceCount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "profileFirstCreatedDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "time"
            },
            {
              "type": "null"
            }
          ]
        },
        "bestTimeToContactEndTime": {
          "anyOf": [
            {
              "type": "string",
              "format": "time"
            },
            {
              "type": "null"
            }
          ]
        },
        "party": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "contactPointType": {
          "type": "array",
          "items": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "object",
                "additionalProperties": true,
                "required": [
                  "id",
                  "name"
                ],
                "properties": {
                  "id": {
                    "anyOf": [
                      {
                        "type": "string"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "name": {
                    "type": "string"
                  },
                  "optInPriority": {
                    "anyOf": [
                      {
                        "type": "integer"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "auditInfo": {
                    "description": "Defines standard system audit fields available for most types",
                    "type": "object",
                    "example": {
                      "isDeleted": true,
                      "createdBy": "commodo minim dolore est",
                      "updatedBy": "dolor quis nulla",
                      "updatedDate": "1950-01-23T19:52:29.659Z",
                      "createdDate": "1950-01-23T19:52:29.659Z"
                    },
                    "additionalProperties": true,
                    "required": [
                      "isDeleted",
                      "createdBy",
                      "updatedBy",
                      "updatedDate",
                      "createdDate"
                    ],
                    "properties": {
                      "createdDate": {
                        "anyOf": [
                          {
                            "type": "string",
                            "format": "date-time"
                          },
                          {
                            "type": "null"
                          }
                        ],
                        "description": "Timestamp of when the entity was created"
                      },
                      "createdBy": {
                        "type": "string",
                        "description": "Identifies the system or user which created the entity"
                      },
                      "updatedDate": {
                        "anyOf": [
                          {
                            "type": "string",
                            "format": "date-time"
                          },
                          {
                            "type": "null"
                          }
                        ],
                        "description": "Timestamp of when the entity was last updated"
                      },
                      "updatedBy": {
                        "type": "string",
                        "description": "Identifies the system or user which last updated the entity"
                      },
                      "isDeleted": {
                        "anyOf": [
                          {
                            "type": "boolean"
                          },
                          {
                            "type": "null"
                          }
                        ],
                        "description": "Indicates whether or not the entity has been soft-deleted"
                      }
                    }
                  }
                }
              }
            ]
          }
        },
        "forBusinessUse": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "forPersonalUse": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "auditInfo": {
          "description": "Defines standard system audit fields available for most types",
          "type": "object",
          "example": {
            "isDeleted": true,
            "createdBy": "commodo minim dolore est",
            "updatedBy": "dolor quis nulla",
            "updatedDate": "1950-01-23T19:52:29.659Z",
            "createdDate": "1950-01-23T19:52:29.659Z"
          },
          "additionalProperties": true,
          "required": [
            "isDeleted",
            "createdBy",
            "updatedBy",
            "updatedDate",
            "createdDate"
          ],
          "properties": {
            "createdDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was created"
            },
            "createdBy": {
              "type": "string",
              "description": "Identifies the system or user which created the entity"
            },
            "updatedDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was last updated"
            },
            "updatedBy": {
              "type": "string",
              "description": "Identifies the system or user which last updated the entity"
            },
            "isDeleted": {
              "anyOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Indicates whether or not the entity has been soft-deleted"
            }
          }
        }
      }
    }
  }
}

=== leadex/mulesoft-meetup-containerization/api/fins-fis-sys-api/src/main/resources/api/accelerator-cim-market-library/1.2.0/examples/ContactPointLocationExample.json
{
  "contactPointType": [
    {
      "id": "nulla reprehenderit labore exercitation",
      "name": "nulla",
      "optInPriority": null,
      "auditInfo": {
        "isDeleted": null,
        "createdBy": "sint",
        "updatedBy": "ut minim et labore in",
        "updatedDate": null,
        "createdDate": null
      }
    }
  ],
  "id": "Ut commodo",
  "activeFromDate": "2015-08-17",
  "name": "non",
  "primaryFlag": null,
  "forPersonalUse": true,
  "profileOccurrenceCount": -36638499,
  "partyRole": [
    "proident"
  ],
  "profileFirstCreatedDate": null,
  "profileLastUpdatedDate": null,
  "bestTimeToContactEndTime": "00:00:01",
  "party": [
    "magna dolor officia"
  ],
  "auditInfo": {
    "isDeleted": null,
    "createdBy": "nisi",
    "updatedBy": "et minim velit voluptate Lorem",
    "updatedDate": null,
    "createdDate": null
  },
  "activeToDate": null,
  "bestTimeToContactStartTime": "00:00:01",
  "forBusinessUse": null
}

=== leadex/mulesoft-meetup-containerization/api/fins-fis-sys-api/src/main/resources/api/accelerator-cim-market-library/1.2.0/examples/ContactPointExample.json
{
  "contactPointType": [
    "nostrud dolore ullamco ea proident"
  ],
  "id": null,
  "activeFromDate": "1982-03-22",
  "primaryFlag": null,
  "forBusinessUse": null,
  "profileOccurrenceCount": null,
  "profileLastUpdatedDate": "00:00:01",
  "forPersonalUse": false,
  "bestTimeToContactStartTime": null,
  "party": [
    "reprehenderit ex ut et Excepteur"
  ],
  "bestTimeToContactEndTime": "00:00:01",
  "profileFirstCreatedDate": "00:00:01",
  "auditInfo": {
    "isDeleted": null,
    "createdBy": "irure",
    "updatedBy": "ut fugiat",
    "updatedDate": null,
    "createdDate": "1985-06-02T11:17:45.441Z"
  },
  "partyRole": [
    "sint cillum enim ipsum"
  ],
  "activeToDate": null,
  "name": "sint cupidatat dolor in"
}
