=== leadex/mulesoft-meetup-containerization/api/fins-fis-sys-api/src/main/resources/api/accelerator-cim-market-library/1.2.0/jsonSchemas/ContactPointSocialSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/ContactPointSocial",
  "definitions": {
    "ContactPointSocial": {
      "type": "object",
      "example": {
        "socialHandle": "proident laborum sed in",
        "socialNetworkProvider": "ea exercitation enim pariatur",
        "contactPointType": [
          "do"
        ],
        "id": "voluptate",
        "activeFromDate": "2001-08-12",
        "profileLastUpdatedDate": null,
        "followersCount": null,
        "forPersonalUse": null,
        "profilePictureURL": "enim do non minim"
      },
      "additionalProperties": true,
      "required": [
        "socialHandle",
        "socialNetworkProvider",
        "contactPointType",
        "id",
        "activeFromDate"
      ],
      "properties": {
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "name": {
          "type": "string"
        },
        "primaryFlag": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "bestTimeToContactStartTime": {
          "anyOf": [
            {
              "type": "string",
              "format": "time"
            },
            {
              "type": "null"
            }
          ]
        },
        "profileLastUpdatedDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "time"
            },
            {
              "type": "null"
            }
          ]
        },
        "partyRole": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "activeFromDate": {
          "type": "string",
          "format": "date"
        },
        "activeToDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ]
        },
        "profileOccurrenceCount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "profileFirstCreatedDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "time"
            },
            {
              "type": "null"
            }
          ]
        },
        "bestTimeToContactEndTime": {
          "anyOf": [
            {
              "type": "string",
              "format": "time"
            },
            {
              "type": "null"
            }
          ]
        },
        "party": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "contactPointType": {
          "type": "array",
          "items": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "object",
                "additionalProperties": true,
                "required": [
                  "id",
                  "name"
                ],
                "properties": {
                  "id": {
                    "anyOf": [
                      {
                        "type": "string"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "name": {
                    "type": "string"
                  },
                  "optInPriority": {
                    "anyOf": [
                      {
                        "type": "integer"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "auditInfo": {
                    "description": "Defines standard system audit fields available for most types",
                    "type": "object",
                    "example": {
                      "isDeleted": true,
                      "createdBy": "commodo minim dolore est",
                      "updatedBy": "dolor quis nulla",
                      "updatedDate": "1950-01-23T19:52:29.659Z",
                      "createdDate": "1950-01-23T19:52:29.659Z"
                    },
                    "additionalProperties": true,
                    "required": [
                      "isDeleted",
                      "createdBy",
                      "updatedBy",
                      "updatedDate",
                      "createdDate"
                    ],
                    "properties": {
                      "createdDate": {
                        "anyOf": [
                          {
                            "type": "string",
                            "format": "date-time"
                          },
                          {
                            "type": "null"
                          }
                        ],
                        "description": "Timestamp of when the entity was created"
                      },
                      "createdBy": {
                        "type": "string",
                        "description": "Identifies the system or user which created the entity"
                      },
                      "updatedDate": {
                        "anyOf": [
                          {
                            "type": "string",
                            "format": "date-time"
                          },
                          {
                            "type": "null"
                          }
                        ],
                        "description": "Timestamp of when the entity was last updated"
                      },
                      "updatedBy": {
                        "type": "string",
                        "description": "Identifies the system or user which last updated the entity"
                      },
                      "isDeleted": {
                        "anyOf": [
                          {
                            "type": "boolean"
                          },
                          {
                            "type": "null"
                          }
                        ],
                        "description": "Indicates whether or not the entity has been soft-deleted"
                      }
                    }
                  }
                }
              }
            ]
          }
        },
        "forBusinessUse": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "forPersonalUse": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "auditInfo": {
          "description": "Defines standard system audit fields available for most types",
          "type": "object",
          "example": {
            "isDeleted": true,
            "createdBy": "commodo minim dolore est",
            "updatedBy": "dolor quis nulla",
            "updatedDate": "1950-01-23T19:52:29.659Z",
            "createdDate": "1950-01-23T19:52:29.659Z"
          },
          "additionalProperties": true,
          "required": [
            "isDeleted",
            "createdBy",
            "updatedBy",
            "updatedDate",
            "createdDate"
          ],
          "properties": {
            "createdDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was created"
            },
            "createdBy": {
              "type": "string",
              "description": "Identifies the system or user which created the entity"
            },
            "updatedDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was last updated"
            },
            "updatedBy": {
              "type": "string",
              "description": "Identifies the system or user which last updated the entity"
            },
            "isDeleted": {
              "anyOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Indicates whether or not the entity has been soft-deleted"
            }
          }
        },
        "profilePictureURL": {
          "type": "string"
        },
        "followersCount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "socialHandleName": {
          "type": "string"
        },
        "socialFanStatus": {
          "type": "string"
        },
        "socialHandle": {
          "type": "string"
        },
        "socialNetworkProvider": {
          "type": "string"
        }
      }
    }
  }
}

=== leadex/mulesoft-meetup-containerization/api/fins-fis-sys-api/src/main/resources/api/accelerator-cim-market-library/1.2.0/examples/ContactPointSocialExample.json
{
  "socialHandle": "consequat",
  "socialNetworkProvider": "enim",
  "contactPointType": [
    {
      "id": "in aute nulla",
      "name": "et",
      "optInPriority": null,
      "auditInfo": {
        "isDeleted": null,
        "createdBy": "reprehenderit laborum",
        "updatedBy": "aute occaecat ad non",
        "updatedDate": null,
        "createdDate": null
      }
    }
  ],
  "id": "nulla fugiat elit ut",
  "activeFromDate": "2010-12-26",
  "followersCount": 95668626,
  "forPersonalUse": true,
  "bestTimeToContactStartTime": "00:00:01",
  "profileOccurrenceCount": null,
  "forBusinessUse": null,
  "socialHandleName": "ea sed",
  "party": [
    "dolor consectetur exercitation nostrud"
  ],
  "primaryFlag": null
}
