=== leadex/mulesoft-meetup-containerization/api/fins-fis-sys-api/src/main/resources/api/accelerator-cim-market-library/1.2.0/jsonSchemas/PartyAdditionalNameSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/PartyAdditionalName",
  "definitions": {
    "PartyAdditionalName": {
      "type": "object",
      "example": {
        "name": "sit non ipsum",
        "id": "reprehenderit",
        "additionalNameType": "labore sint dolore fugiat",
        "party": [
          "ad"
        ],
        "auditInfo": {
          "isDeleted": true,
          "createdBy": "ut nulla elit esse dolore",
          "updatedBy": "Excepteur commodo elit enim in",
          "updatedDate": null,
          "createdDate": "1941-08-08T18:21:42.114Z"
        }
      },
      "additionalProperties": true,
      "required": [
        "name",
        "id",
        "additionalNameType"
      ],
      "properties": {
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "name": {
          "type": "string"
        },
        "additionalNameType": {
          "type": "string"
        },
        "party": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "auditInfo": {
          "description": "Defines standard system audit fields available for most types",
          "type": "object",
          "example": {
            "isDeleted": true,
            "createdBy": "commodo minim dolore est",
            "updatedBy": "dolor quis nulla",
            "updatedDate": "1950-01-23T19:52:29.659Z",
            "createdDate": "1950-01-23T19:52:29.659Z"
          },
          "additionalProperties": true,
          "required": [
            "isDeleted",
            "createdBy",
            "updatedBy",
            "updatedDate",
            "createdDate"
          ],
          "properties": {
            "createdDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was created"
            },
            "createdBy": {
              "type": "string",
              "description": "Identifies the system or user which created the entity"
            },
            "updatedDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was last updated"
            },
            "updatedBy": {
              "type": "string",
              "description": "Identifies the system or user which last updated the entity"
            },
            "isDeleted": {
              "anyOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Indicates whether or not the entity has been soft-deleted"
            }
          }
        }
      }
    }
  }
}

=== leadex/mulesoft-meetup-containerization/api/fins-fis-sys-api/src/main/resources/api/accelerator-cim-market-library/1.2.0/examples/PartyAdditionalNameExample.json
{
  "name": "Lorem pariatur",
  "id": "sit eu ut deserunt",
  "additionalNameType": "adipisicing deserunt et",
  "auditInfo": {
    "isDeleted": null,
    "createdBy": "dolore elit enim",
    "updatedBy": "sint pariatur velit",
    "updatedDate": "2019-07-25T01:20:09.479Z",
    "createdDate": "1998-09-27T10:00:23.308Z"
  },
  "party": [
    "dolore reprehenderit"
  ]
}
