=== leadex/mulesoft-meetup-containerization/api/fins-fis-sys-api/src/main/resources/api/accelerator-cim-market-library/1.2.0/jsonSchemas/PersonEmploymentSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/PersonEmployment",
  "definitions": {
    "PersonEmployment": {
      "type": "object",
      "example": {
        "occupationText": "ex labore dolor in",
        "id": "enim in ut",
        "employerName": "reprehenderit ut amet aute nulla",
        "employmentStatus": "irure labore dolore",
        "auditInfo": {
          "isDeleted": false,
          "createdBy": "qui ad consectetur",
          "updatedBy": "minim non",
          "updatedDate": "1951-12-09T03:43:28.26Z",
          "createdDate": "2014-06-16T23:02:00.186Z"
        },
        "positionText": "ea reprehenderit",
        "employerAddressLine3": "cillum do",
        "employerContactPointAddress": [
          "amet"
        ],
        "endDate": "2006-05-05",
        "individual": [
          "commodo Duis ullamco cillum"
        ],
        "annualIncome": null,
        "employerAddressLine1": "cillum",
        "employerPostalCodeText": "magna ex velit deserunt Lorem",
        "employerAddressLine4": "exercitation",
        "employerPhoneNumber": "in eu velit",
        "employerCityName": "occaecat officia anim",
        "startDate": "1981-12-25",
        "employerAddressLine2": "est aliqua"
      },
      "additionalProperties": true,
      "required": [
        "occupationText",
        "id",
        "employerName",
        "employmentStatus"
      ],
      "properties": {
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "employmentStatus": {
          "type": "string"
        },
        "positionText": {
          "type": "string"
        },
        "employerContactPointAddress": {
          "type": "array",
          "items": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "object",
                "additionalProperties": true,
                "required": [
                  "addressLine1",
                  "contactPointType",
                  "id",
                  "activeFromDate"
                ],
                "properties": {
                  "id": {
                    "anyOf": [
                      {
                        "type": "string"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "name": {
                    "type": "string"
                  },
                  "primaryFlag": {
                    "anyOf": [
                      {
                        "type": "boolean"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "bestTimeToContactStartTime": {
                    "anyOf": [
                      {
                        "type": "string",
                        "format": "time"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "profileLastUpdatedDate": {
                    "anyOf": [
                      {
                        "type": "string",
                        "format": "time"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "partyRole": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  },
                  "activeFromDate": {
                    "type": "string",
                    "format": "date"
                  },
                  "activeToDate": {
                    "anyOf": [
                      {
                        "type": "string",
                        "format": "date"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "profileOccurrenceCount": {
                    "anyOf": [
                      {
                        "type": "integer"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "profileFirstCreatedDate": {
                    "anyOf": [
                      {
                        "type": "string",
                        "format": "time"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "bestTimeToContactEndTime": {
                    "anyOf": [
                      {
                        "type": "string",
                        "format": "time"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "party": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  },
                  "contactPointType": {
                    "type": "array",
                    "items": {
                      "anyOf": [
                        {
                          "type": "string"
                        },
                        {
                          "type": "object",
                          "additionalProperties": true,
                          "required": [
                            "id",
                            "name"
                          ],
                          "properties": {
                            "id": {
                              "anyOf": [
                                {
                                  "type": "string"
                                },
                                {
                                  "type": "null"
                                }
                              ]
                            },
                            "name": {
                              "type": "string"
                            },
                            "optInPriority": {
                              "anyOf": [
                                {
                                  "type": "integer"
                                },
                                {
                                  "type": "null"
                                }
                              ]
                            },
                            "auditInfo": {
                              "description": "Defines standard system audit fields available for most types",
                              "type": "object",
                              "example": {
                                "isDeleted": true,
                                "createdBy": "commodo minim dolore est",
                                "updatedBy": "dolor quis nulla",
                                "updatedDate": "1950-01-23T19:52:29.659Z",
                                "createdDate": "1950-01-23T19:52:29.659Z"
                              },
                              "additionalProperties": true,
                              "required": [
                                "isDeleted",
                                "createdBy",
                                "updatedBy",
                                "updatedDate",
                                "createdDate"
                              ],
                              "properties": {
                                "createdDate": {
                                  "anyOf": [
                                    {
                                      "type": "string",
                                      "format": "date-time"
                                    },
                                    {
                                      "type": "null"
                                    }
                                  ],
                                  "description": "Timestamp of when the entity was created"
                                },
                                "createdBy": {
                                  "type": "string",
                                  "description": "Identifies the system or user which created the entity"
                                },
                                "updatedDate": {
                                  "anyOf": [
                                    {
                                      "type": "string",
                                      "format": "date-time"
                                    },
                                    {
                                      "type": "null"
                                    }
                                  ],
                                  "description": "Timestamp of when the entity was last updated"
                                },
                                "updatedBy": {
                                  "type": "string",
                                  "description": "Identifies the system or user which last updated the entity"
                                },
                                "isDeleted": {
                                  "anyOf": [
                                    {
                                      "type": "boolean"
                                    },
                                    {
                                      "type": "null"
                                    }
                                  ],
                                  "description": "Indicates whether or not the entity has been soft-deleted"
                                }
                              }
                            }
                          }
                        }
                      ]
                    }
                  },
                  "forBusinessUse": {
                    "anyOf": [
                      {
                        "type": "boolean"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "forPersonalUse": {
                    "anyOf": [
                      {
                        "type": "boolean"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "auditInfo": {
                    "description": "Defines standard system audit fields available for most types",
                    "type": "object",
                    "example": {
                      "isDeleted": true,
                      "createdBy": "commodo minim dolore est",
                      "updatedBy": "dolor quis nulla",
                      "updatedDate": "1950-01-23T19:52:29.659Z",
                      "createdDate": "1950-01-23T19:52:29.659Z"
                    },
                    "additionalProperties": true,
                    "required": [
                      "isDeleted",
                      "createdBy",
                      "updatedBy",
                      "updatedDate",
                      "createdDate"
                    ],
                    "properties": {
                      "createdDate": {
                        "anyOf": [
                          {
                            "type": "string",
                            "format": "date-time"
                          },
                          {
                            "type": "null"
                          }
                        ],
                        "description": "Timestamp of when the entity was created"
                      },
                      "createdBy": {
                        "type": "string",
                        "description": "Identifies the system or user which created the entity"
                      },
                      "updatedDate": {
                        "anyOf": [
                          {
                            "type": "string",
                            "format": "date-time"
                          },
                          {
                            "type": "null"
                          }
                        ],
                        "description": "Timestamp of when the entity was last updated"
                      },
                      "updatedBy": {
                        "type": "string",
                        "description": "Identifies the system or user which last updated the entity"
                      },
                      "isDeleted": {
                        "anyOf": [
                          {
                            "type": "boolean"
                          },
                          {
                            "type": "null"
                          }
                        ],
                        "description": "Indicates whether or not the entity has been soft-deleted"
                      }
                    }
                  },
                  "isUsedForShipping": {
                    "anyOf": [
                      {
                        "type": "boolean"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "stateProvinceName": {
                    "type": "string"
                  },
                  "addressLine3": {
                    "type": "string"
                  },
                  "countryName": {
                    "type": "string"
                  },
                  "postalCodeText": {
                    "type": "string"
                  },
                  "geoLatitude": {
                    "anyOf": [
                      {
                        "type": "integer"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "addressLine2": {
                    "type": "string"
                  },
                  "addressLine4": {
                    "type": "string"
                  },
                  "geoAccuracy": {
                    "anyOf": [
                      {
                        "type": "integer"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "contactPhone": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  },
                  "geoLongitude": {
                    "anyOf": [
                      {
                        "type": "integer"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "addressLine1": {
                    "type": "string"
                  },
                  "cityName": {
                    "type": "string"
                  },
                  "isUsedForBilling": {
                    "anyOf": [
                      {
                        "type": "boolean"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  }
                }
              }
            ]
          }
        },
        "employerAddressLine3": {
          "type": "string"
        },
        "endDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ]
        },
        "startDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ]
        },
        "occupationText": {
          "type": "string"
        },
        "employerName": {
          "type": "string"
        },
        "employerAddressLine4": {
          "type": "string"
        },
        "employerAddressLine1": {
          "type": "string"
        },
        "annualIncome": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ]
        },
        "employerCityName": {
          "type": "string"
        },
        "individual": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "employerAddressLine2": {
          "type": "string"
        },
        "employerPostalCodeText": {
          "type": "string"
        },
        "employerPhoneNumber": {
          "type": "string"
        },
        "auditInfo": {
          "description": "Defines standard system audit fields available for most types",
          "type": "object",
          "example": {
            "isDeleted": true,
            "createdBy": "commodo minim dolore est",
            "updatedBy": "dolor quis nulla",
            "updatedDate": "1950-01-23T19:52:29.659Z",
            "createdDate": "1950-01-23T19:52:29.659Z"
          },
          "additionalProperties": true,
          "required": [
            "isDeleted",
            "createdBy",
            "updatedBy",
            "updatedDate",
            "createdDate"
          ],
          "properties": {
            "createdDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was created"
            },
            "createdBy": {
              "type": "string",
              "description": "Identifies the system or user which created the entity"
            },
            "updatedDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was last updated"
            },
            "updatedBy": {
              "type": "string",
              "description": "Identifies the system or user which last updated the entity"
            },
            "isDeleted": {
              "anyOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Indicates whether or not the entity has been soft-deleted"
            }
          }
        }
      }
    }
  }
}

=== leadex/mulesoft-meetup-containerization/api/fins-fis-sys-api/src/main/resources/api/accelerator-cim-market-library/1.2.0/examples/PersonEmploymentExample.json
{
  "occupationText": "consequat nulla minim",
  "id": "Lorem adipisicing laborum ex sit",
  "employerName": "in",
  "employmentStatus": "eu pariatur quis",
  "annualIncome": -44890748,
  "employerAddressLine3": "fugiat",
  "employerPostalCodeText": "incididunt id",
  "auditInfo": {
    "isDeleted": null,
    "createdBy": "dolor pariatur tempor amet",
    "updatedBy": "in",
    "updatedDate": "1967-12-09T13:10:15.689Z",
    "createdDate": null
  },
  "employerAddressLine1": "incididunt dolor non",
  "endDate": "1959-06-03",
  "employerAddressLine2": "Lorem consequat",
  "employerContactPointAddress": [
    {
      "addressLine1": "laboris sed sint velit",
      "contactPointType": [
        "reprehenderit ut est elit"
      ],
      "id": null,
      "activeFromDate": "1996-11-16",
      "addressLine4": "Ut tempor aliquip consectetur eu",
      "forBusinessUse": true,
      "addressLine3": "Lorem cillum do occaecat",
      "bestTimeToContactStartTime": null,
      "isUsedForBilling": null,
      "addressLine2": "id nulla aute sit Lorem",
      "postalCodeText": "ullamco Duis",
      "name": "deserunt dolore",
      "bestTimeToContactEndTime": "00:00:01",
      "forPersonalUse": null,
      "countryName": "laboris sint cillum officia elit",
      "contactPhone": [
        "laborum adipisicing eiusmod in amet"
      ]
    }
  ],
  "positionText": "id nulla ad nisi",
  "individual": [
    "magna ad labore"
  ],
  "employerPhoneNumber": "ad Excepteur et anim",
  "startDate": "1951-07-07",
  "employerAddressLine4": "labore commodo nostrud occaecat",
  "employerCityName": "proident amet nostrud"
}
