=== leadex/mulesoft-meetup-containerization/api/fins-fis-sys-api/src/main/resources/api/accelerator-cim-market-library/1.2.0/jsonSchemas/PersonEducationSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/PersonEducation",
  "definitions": {
    "PersonEducation": {
      "type": "object",
      "example": {
        "educationLevel": "nisi minim do",
        "id": "culpa non dolore esse",
        "institutionName": "do incididunt labore tempor",
        "educationName": "ea aliqua cupidatat tempor",
        "auditInfo": {
          "isDeleted": null,
          "createdBy": "mollit cupidatat Duis",
          "updatedBy": "deserunt velit",
          "updatedDate": null,
          "createdDate": null
        }
      },
      "additionalProperties": true,
      "required": [
        "educationLevel",
        "id",
        "institutionName",
        "educationName"
      ],
      "properties": {
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "educationLevel": {
          "type": "string"
        },
        "educationName": {
          "type": "string"
        },
        "graduationDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ]
        },
        "individual": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "institutionName": {
          "type": "string"
        },
        "auditInfo": {
          "description": "Defines standard system audit fields available for most types",
          "type": "object",
          "example": {
            "isDeleted": true,
            "createdBy": "commodo minim dolore est",
            "updatedBy": "dolor quis nulla",
            "updatedDate": "1950-01-23T19:52:29.659Z",
            "createdDate": "1950-01-23T19:52:29.659Z"
          },
          "additionalProperties": true,
          "required": [
            "isDeleted",
            "createdBy",
            "updatedBy",
            "updatedDate",
            "createdDate"
          ],
          "properties": {
            "createdDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was created"
            },
            "createdBy": {
              "type": "string",
              "description": "Identifies the system or user which created the entity"
            },
            "updatedDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was last updated"
            },
            "updatedBy": {
              "type": "string",
              "description": "Identifies the system or user which last updated the entity"
            },
            "isDeleted": {
              "anyOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Indicates whether or not the entity has been soft-deleted"
            }
          }
        }
      }
    }
  }
}

=== leadex/mulesoft-meetup-containerization/api/fins-fis-sys-api/src/main/resources/api/accelerator-cim-market-library/1.2.0/examples/PersonEducationExample.json
{
  "educationLevel": "enim",
  "id": null,
  "institutionName": "Duis nostrud",
  "educationName": "esse proident",
  "auditInfo": {
    "isDeleted": true,
    "createdBy": "Ut consectetur",
    "updatedBy": "occaecat sit sunt",
    "updatedDate": null,
    "createdDate": null
  },
  "individual": [
    "amet dolore Excepteur magna"
  ],
  "graduationDate": null
}
