=== leadex/mulesoft-meetup-containerization/api/fins-fis-sys-api/src/main/resources/api/accelerator-cim-market-library/1.2.0/jsonSchemas/PersonLifeEventSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/PersonLifeEvent",
  "definitions": {
    "PersonLifeEvent": {
      "type": "object",
      "example": {
        "personLifeEventDateTime": "00:00:01",
        "personLifeEventType": "occaecat in Ut",
        "id": null,
        "individual": [
          "dolore enim"
        ],
        "auditInfo": {
          "isDeleted": true,
          "createdBy": "quis nulla nostrud enim culpa",
          "updatedBy": "ullamco ut officia ea",
          "updatedDate": null,
          "createdDate": null
        }
      },
      "additionalProperties": true,
      "required": [
        "personLifeEventDateTime",
        "personLifeEventType",
        "id"
      ],
      "properties": {
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "individual": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "personLifeEventDateTime": {
          "type": "string",
          "format": "time"
        },
        "personLifeEventType": {
          "type": "string"
        },
        "auditInfo": {
          "description": "Defines standard system audit fields available for most types",
          "type": "object",
          "example": {
            "isDeleted": true,
            "createdBy": "commodo minim dolore est",
            "updatedBy": "dolor quis nulla",
            "updatedDate": "1950-01-23T19:52:29.659Z",
            "createdDate": "1950-01-23T19:52:29.659Z"
          },
          "additionalProperties": true,
          "required": [
            "isDeleted",
            "createdBy",
            "updatedBy",
            "updatedDate",
            "createdDate"
          ],
          "properties": {
            "createdDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was created"
            },
            "createdBy": {
              "type": "string",
              "description": "Identifies the system or user which created the entity"
            },
            "updatedDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was last updated"
            },
            "updatedBy": {
              "type": "string",
              "description": "Identifies the system or user which last updated the entity"
            },
            "isDeleted": {
              "anyOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Indicates whether or not the entity has been soft-deleted"
            }
          }
        }
      }
    }
  }
}

=== leadex/mulesoft-meetup-containerization/api/fins-fis-sys-api/src/main/resources/api/accelerator-cim-market-library/1.2.0/examples/PersonLifeEventExample.json
{
  "personLifeEventDateTime": "00:00:01",
  "personLifeEventType": "ullamco sed magna mollit",
  "id": null,
  "individual": [
    "dolor commodo"
  ],
  "auditInfo": {
    "isDeleted": true,
    "createdBy": "aute",
    "updatedBy": "dolor nulla do nisi sed",
    "updatedDate": null,
    "createdDate": "1946-11-22T14:08:46.496Z"
  }
}
